### PR TITLE
download page modifications

### PR DESCRIPTION
**Pull request by PetrMc**

### CODE REVIEW

**Comment by PetrMc** [comment]
Hi Adityo, can you have a look why my changes are getting rejected? thanks a lot!

**Comment by lunchboxav** [comment]
@PetrMc I see this error in Netlify

```
Error: Error building site: "/opt/build/repo/content/download/_index.en.md:15:1": failed to render shortcode "dwn_getistio": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/dwn_getistio.html:20:7": execute of template failed: template: shortcodes/dwn_getistio.html:20:7: executing "shortcodes/dwn_getistio.html" at <(gt $t2 0) and (gt 5184000000 $t2)>: can't give argument to non-function gt $t2 0
```

something wrong with the shortcode?

**Comment by lunchboxav** [comment]
it's error on my local as well, let me check it out in more detail

**Comment by lunchboxav** [comment]
fixed @PetrMc , I just fix this line in `dwn_getistio.html`. Previously you have this:

```
{{ if (gt $t2 0) and (gt 5184000000 $t2) }}	   
```

I replace it to 

```
{{ if and (gt $t2 0) (gt 5184000000 $t2) }}	   
```

Hugo if syntax can sometimes be weird :D

You can merge this now @PetrMc. Thank you for the nice improvement on EOS.

**Review by lunchboxav — APPROVED** [review]

**Comment by PetrMc** [comment]
Thanks a lot Sir!

**Pull request merged**
